version: '3'

services:
    prototype:
        build:
            context: ./
            dockerfile: Dockerfile
        links: 
          - database
    database:
        image: postgres:10
        environment:
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=dbpassword
            - POSTGRES_DB=dbsample
        ports:
            - 5432:5432
        tmpfs:
          - /var/lib/postgresql/data:rw,noexec,nosuid,size=400m
